color:
  palette:
    white: "#ffffff"
    grey233: "#e9e9e9"
    grey217: "#d9d9d9"
    grey200: "#c8c8c8"
    grey225: "#e1e1e1"
    grey37: "#252525"
    black: "#000000"
  foreground: #212529
  background: white
  primary: #2c3e50

logo:
  path: ohdsi

typography:
  base:
    family: Arial
    size: "11"

defaults:
  shiny:
    theme:
      preset: flatly
  visOmopResults:
    plot:
      font_family: sans
      font_size: "11"
      background_color: white
      header_color: grey225
      header_text_color: black
      header_text_bold: TRUE
      grid_major_color: grey217
      axis_color: grey37
      border_color: grey225
      legend_position: "right"
    table:
      font_family: Arial
      font_size: "10"
      header:
        background_color: grey200
        text_bold: TRUE
        border_color: grey200
        align: center
      header_name:
        background_color: grey217
        text_bold: TRUE
        border_color: grey200
        align: center
      header_level:
        background_color: grey225
        text_bold: TRUE
        border_color: grey200
        align: center
      column_name:
        background_color: grey225
        text_bold: TRUE
        border_color: grey200
        align: center
      group_label:
        background_color: grey233
        text_bold: TRUE
        border_color: grey200
      title:
        background_color: transparent
        border_color: grey225
        font_size: 15
        align: center
        text_bold: TRUE
      subtitle:
        background_color: transparent
        align: center
        border_color: grey225
        font_size: 12
        text_bold: TRUE
      body:
        background_color: transparent
        border_color: grey200
