brand:
  color:
    palette:
      white: "#ffffff"
      grey233: "#e9e9e9"
      grey217: "#d9d9d9"
      grey200: "#c8c8c8"
      grey225: "#e1e1e1"
      grey37: "#252525"
      black: "#000000"
    background: white
    foreground: grey225
    primary: grey225

  typography:
    base: Arial
    base-font-size: 11
    table: Arial
    table-font-size: 10
    plot: sans
    plot-font-size: 11

  plot:
    background-color: white
    header-color: grey225
    header-text-color: black
    grid-major-color: grey217
    axis-color: grey37
    border-color: grey225
    legend-position: "right"

  table:
    header:
      background-color: grey200
      text-bold: TRUE
      border-color: grey200
      align: center
    header-name:
      background-color: grey217
      text-bold: TRUE
      border-color: grey200
      align: center
    header-level:
      background-color: grey225
      text-bold: TRUE
      border-color: grey200
      align: center
    column-name:
      background-color: grey225
      text-bold: TRUE
      border-color: grey200
      align: center
    group-label:
      background-color: grey233
      text-bold: TRUE
      border-color: grey200
    title:
      background-color: transparent
      border-color: grey225
      font-size: 15
      align: center
      text-bold: TRUE
    subtitle:
      background-color: transparent
      align: center
      border-color: grey225
      font-size: 12
      text-bold: TRUE
    body:
      background-color: transparent
      border-color: grey200
